### ISSUE TITLE
I met a problom 

### ISSUE THREAD

**Issue by shun1249844726** [Yalantis/ToDoList#4]
我原本的工程中使用到了 butterknife:8.4.0  
新添加这个工程就会遇到冲突。。不知道怎么解决

**Comment by TeeRawk** [comment]
Hello , @shun1249844726 , please ,can write you issue in English.

**Comment by 3ffusi0on** [comment]
From google translate :

> I used the original project with butterknife: 8.4.0
> The new project will encounter a conflict. I do not know how to solve it

**Comment by KucherenkoIhor** [comment]
Hello, @3ffusi0on did you use [exclude](https://www.linkedin.com/pulse/how-find-dependencies-particular-dependency-gradle-hesamedin-kamalan-1)?
As I can see this library uses 8.2.1 version of butterknife. You can see it in [build.gradle](https://github.com/Yalantis/ToDoList/blob/master/library/build.gradle) file.

**Comment by 3ffusi0on** [comment]
@KucherenkoIhor It's not my own problem. I was just translating @shun1249844726 issue for @TeeRawk who requested english :)

**Comment by shun1249844726** [comment]
I have already solved the problem,I deleted some duplicate files.Thank you for your help.

**Comment by senpl** [comment]
Is this issue to close?

**Comment by shun1249844726** [comment]
yes,I close it
